import json

CONFIG_MODEL_KEY = "Model"
CONFIG_MODEL_CKPTSAVEPATH_SUBKEY = "PathCKPT"
CONFIG_MODEL_CKPTFILENAME_SUBKEY = "NameCKPT"
CONFIG_MODEL_TYPE_SUBKEY = "Type"
CONFIG_ENVIRONMENT_KEY = "Environment"
CONFIG_ENVIRONMENT_TYPE_SUBKEY = "Type"
CONFIG_ENVIRONMENT_STATEDIMENSIONS_SUBKEY = "StateDimensions"
CONFIG_TRAIN_KEY = "Train"
CONFIG_TRAIN_EPOCHS_SUBKEY = "Epochs"
CONFIG_TRAIN_EPOCHS_MAIN_SUBSUBKEY = "Main"
CONFIG_TRAIN_EPOCHS_SAMPLING_SUBSUBKEY = "Sampling"
CONFIG_TRAIN_EPOCHS_BACKPROP_SUBSUBKEY = "Backprop"
CONFIG_TRAIN_DISCOUNTFACTOR_SUBKEY = "DiscountFactor"
CONFIG_TRAIN_EPSILON_SUBKEY = "Epsilon"
CONFIG_TRAIN_DROPOUTPROB_SUBKEY = "DropoutProb"
CONFIG_TRAIN_REPLAYBUFFERSIZE_SUBKEY = "ReplayBufferSize"
CONFIG_TRAIN_SAMPLESIZE_SUBKEY = "SampleSize"
CONFIG_DEBUG_KEY = "Debug"
CONFIG_DEBUG_INTERVALS_SUBKEY = "Intervals"
CONFIG_DEBUG_INTERVALS_PRINTSTEPS_SUBSUBKEY = "PrintSteps"
CONFIG_DEBUG_INTERVALS_SAVECKPT_SUBSUBKEY = "SaveCKPT"

class ConfigLoader:
	def __init__(self, file_json):
		f = open(file_json)
		self._config = json.load(f)
		self.load_configs()
		f.close()
		
	def load_configs(self):
		self.model_type = self._config[CONFIG_MODEL_KEY][CONFIG_MODEL_TYPE_SUBKEY]
		self.ckpt_save_path = self._config[CONFIG_MODEL_KEY][CONFIG_MODEL_CKPTSAVEPATH_SUBKEY]
		self.ckpt_file_name = self._config[CONFIG_MODEL_KEY][CONFIG_MODEL_CKPTFILENAME_SUBKEY]
		self.env_type = self._config[CONFIG_ENVIRONMENT_KEY][CONFIG_ENVIRONMENT_TYPE_SUBKEY]
		self.env_dims = self._config[CONFIG_ENVIRONMENT_KEY][CONFIG_ENVIRONMENT_STATEDIMENSIONS_SUBKEY]
		self.num_epochs_main = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_EPOCHS_SUBKEY][CONFIG_TRAIN_EPOCHS_MAIN_SUBSUBKEY]
		self.num_epochs_sampling = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_EPOCHS_SUBKEY][CONFIG_TRAIN_EPOCHS_SAMPLING_SUBSUBKEY]
		self.num_epochs_backprop = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_EPOCHS_SUBKEY][CONFIG_TRAIN_EPOCHS_BACKPROP_SUBSUBKEY]
		self.replay_buffer_size =  self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_REPLAYBUFFERSIZE_SUBKEY]
		self.sample_size = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_SAMPLESIZE_SUBKEY]
		self.discount_factor = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_DISCOUNTFACTOR_SUBKEY]
		self.epsilon = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_EPSILON_SUBKEY]
		self.dropout_prob = self._config[CONFIG_TRAIN_KEY][CONFIG_TRAIN_DROPOUTPROB_SUBKEY]
		self.print_steps_period = self._config[CONFIG_DEBUG_KEY][CONFIG_DEBUG_INTERVALS_SUBKEY][CONFIG_DEBUG_INTERVALS_PRINTSTEPS_SUBSUBKEY]
		self.save_interval_ckpt = self._config[CONFIG_DEBUG_KEY][CONFIG_DEBUG_INTERVALS_SUBKEY][CONFIG_DEBUG_INTERVALS_SAVECKPT_SUBSUBKEY]

